services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./prisma/dev.db
      - PORT=3000
      - MAILOPOST_API_URL=https://api.mailopost.ru/v1
      - MAILOPOST_API_TOKEN=0e214eeceb83783a7ed4dc025a0175b1
      - MAILOPOST_FROM_EMAIL=noreply@burker-watches.ru
      - MAILOPOST_FROM_NAME=Burker Watches
      - ADMIN_EMAIL=info@kondratov.online
    working_dir: /app
    volumes:
      # Монтируем весь код для hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./prisma/dev.db:/app/prisma/dev.db
      - ./public/promo:/app/public/promo
    command: npm run dev
    restart: unless-stopped
